<!--
  ~ Copyright 2012-2019 Oscar Westra van Holthe - Kind
  ~
  ~ Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in
  ~ compliance with the License.
  ~
  ~ You may obtain a copy of the License at
  ~
  ~     http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~ Unless required by applicable law or agreed to in writing, software distributed under the License is
  ~ distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
  ~ implied. See the License for the specific language governing permissions and limitations under the
  ~ License.
  -->
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>net.sf.opk</groupId>
	<artifactId>opk-parent</artifactId>
	<version>6</version>
	<packaging>pom</packaging>

	<name>Parent POM</name>
	<description>Parent POM for all projects with group ID net.sf.opk.</description>

	<url>http://opk.sf.net/${project.artifactId}/</url>
	<inceptionYear>2011</inceptionYear>
	<scm>
		<url>http://svn.code.sf.net/p/opk/code/opk-parent/trunk/</url>
		<connection>scm:svn:svn://svn.code.sf.net/p/opk/code/opk-parent/trunk/</connection>
		<developerConnection>scm:svn:https://svn.code.sf.net/p/opk/code/opk-parent/trunk/</developerConnection>
	</scm>
	<licenses>
		<license>
			<name>Apache 2</name>
			<url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
			<distribution>repo</distribution>
			<comments>A business-friendly OSS license</comments>
		</license>
	</licenses>
	<developers>
		<developer>
			<id>opwvhk</id>
			<name>Oscar Westra van Holthe - Kind</name>
			<email>oscar@westravanholthe.nl</email>
			<url>http://oscar.westravanholthe.nl/</url>
			<roles>
				<role>architect</role>
				<role>developer</role>
			</roles>
			<timezone>1</timezone>
		</developer>
	</developers>
	<organization>
		<!-- Not really an organization, but the owner of the copyrights. -->
		<name>Oscar Westra van Holthe - Kind</name>
		<url>http://oscar.westravanholthe.nl/</url>
	</organization>
	<distributionManagement>
		<snapshotRepository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/content/repositories/snapshots</url>
		</snapshotRepository>
		<repository>
			<id>ossrh</id>
			<url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
		</repository>
		<site>
			<id>opk.sf.net</id>
			<name>Project website at SourceForge</name>
			<url>scpexe://okind@shell.sourceforge.net/home/project-web/opk/htdocs</url>
		</site>
	</distributionManagement>
	<properties>
		<!-- Build configurations -->
		<targetJdkVersion>1.8</targetJdkVersion>
		<defaultFileEncoding>UTF-8</defaultFileEncoding>
		<maven.build.timestamp.format>yyyyMMdd.HHmmss</maven.build.timestamp.format>

		<maven.compiler.source>${targetJdkVersion}</maven.compiler.source>
		<maven.compiler.target>${targetJdkVersion}</maven.compiler.target>
		<maven.compiler.testSource>${targetJdkVersion}</maven.compiler.testSource>
		<maven.compiler.testTarget>${targetJdkVersion}</maven.compiler.testTarget>
		<project.build.sourceEncoding>${defaultFileEncoding}</project.build.sourceEncoding>
		<project.reporting.outputEncoding>${defaultFileEncoding}</project.reporting.outputEncoding>
	</properties>
	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-enforcer-plugin</artifactId>
				<version>3.0.0-M2</version>
				<executions>
					<execution>
						<id>enforce-basics-and-sane-dependencies</id>
						<goals>
							<goal>enforce</goal>
						</goals>
						<configuration>
							<rules>
								<requireJavaVersion>
									<version>[1.8,)</version>
								</requireJavaVersion>
								<requireMavenVersion>
									<version>[3.0,)</version>
								</requireMavenVersion>
								<requireUpperBoundDeps/>
							</rules>
							<fail>true</fail>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-report-plugin</artifactId>
				<version>2.22.1</version>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.3</version>
				<executions>
					<execution>
						<goals>
							<goal>prepare-agent</goal>
						</goals>
					</execution>
					<execution>
						<id>report</id>
						<phase>post-integration-test</phase>
						<goals>
							<goal>report</goal>
						</goals>
						<configuration>
							<outputDirectory>${project.build.directory}/jacoco</outputDirectory>
						</configuration>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-source-plugin</artifactId>
				<version>3.0.1</version>
				<executions>
					<execution>
						<id>attach-sources</id>
						<goals>
							<goal>jar-no-fork</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-site-plugin</artifactId>
				<version>3.7.1</version>
				<dependencies>
					<dependency>
						<groupId>org.apache.maven.doxia</groupId>
						<artifactId>doxia-module-markdown</artifactId>
						<version>1.8</version>
					</dependency>
				</dependencies>
				<executions>
					<execution>
						<id>attach-descriptor</id>
						<goals>
							<goal>attach-descriptor</goal>
						</goals>
					</execution>
				</executions>
				<configuration>
					<validate>true</validate>
				</configuration>
			</plugin>
		</plugins>
		<extensions>
			<!-- For URLs, add SSH / SCP / SFTP support -->
			<extension>
				<groupId>org.apache.maven.wagon</groupId>
				<artifactId>wagon-ssh-external</artifactId>
				<version>3.3.2</version>
			</extension>
		</extensions>
	</build>
	<reporting>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-project-info-reports-plugin</artifactId>
				<version>3.0.0</version>
				<reportSets>
					<reportSet>
						<reports>
							<!-- Note: do not omit the index report unless you're creating an index.html elsewhere. -->
							<report>index</report>
							<report>modules</report>
							<report>licenses</report>
							<report>scm</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-surefire-report-plugin</artifactId>
				<version>2.22.1</version>
			</plugin>
			<plugin>
				<groupId>org.jacoco</groupId>
				<artifactId>jacoco-maven-plugin</artifactId>
				<version>0.8.3</version>
				<reportSets>
					<reportSet>
						<reports>
							<report>report</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-javadoc-plugin</artifactId>
				<version>3.0.1</version>
				<reportSets>
					<reportSet>
						<reports>
							<report>javadoc</report>
						</reports>
					</reportSet>
				</reportSets>
			</plugin>
		</plugins>
	</reporting>
	<profiles>
		<profile>
			<id>release</id>
			<build>
				<plugins>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-enforcer-plugin</artifactId>
						<version>3.0.0-M2</version>
						<executions>
							<execution>
								<id>additionally-enforce-no-snapshots</id>
								<goals>
									<goal>enforce</goal>
								</goals>
								<configuration>
									<rules>
										<requireReleaseVersion/>
										<requireReleaseDeps/>
									</rules>
									<fail>true</fail>
								</configuration>
							</execution>
						</executions>
					</plugin>
					<plugin>
						<groupId>org.apache.maven.plugins</groupId>
						<artifactId>maven-gpg-plugin</artifactId>
						<version>1.6</version>
						<executions>
							<execution>
								<id>sign-artifacts</id>
								<phase>verify</phase>
								<goals>
									<goal>sign</goal>
								</goals>
							</execution>
						</executions>
						<configuration>
							<!-- Note: this configuration assumes you have and want to use your default GnuPG key -->
							<gpgArguments>
								<arg>--pinentry-mode</arg>
								<arg>loopback</arg>
							</gpgArguments>
							<passphraseServerId>gpg.passphrase</passphraseServerId>
						</configuration>
					</plugin>
					<plugin>
						<groupId>org.sonatype.plugins</groupId>
						<artifactId>nexus-staging-maven-plugin</artifactId>
						<version>1.6.8</version>
						<extensions>true</extensions>
						<configuration>
							<serverId>ossrh</serverId>
							<nexusUrl>https://oss.sonatype.org/</nexusUrl>
							<autoReleaseAfterClose>true</autoReleaseAfterClose>
						</configuration>
					</plugin>
				</plugins>
			</build>
		</profile>
		<profile>
			<id>disable-test-report-for-parent-pom</id>
			<!-- Unlike the other reports, the surefire report does not skip itself if there is nothing to report. -->
			<activation>
				<file>
					<missing>src/test/java</missing>
				</file>
			</activation>
			<properties>
				<skipSurefireReport>true</skipSurefireReport>
			</properties>
		</profile>
	</profiles>
</project>
